package com.hurricane.coupon.dao;

import com.hurricane.coupon.entity.CouponLog;

public interface CouponLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_log
     *
     * @mbggenerated
     */
    int insert(CouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_log
     *
     * @mbggenerated
     */
    int insertSelective(CouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_log
     *
     * @mbggenerated
     */
    CouponLog selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CouponLog record);
}