package com.hurricane.coupon.dao;

import com.hurricane.coupon.entity.ManageLog;

public interface ManageLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_log
     *
     * @mbggenerated
     */
    int insert(ManageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_log
     *
     * @mbggenerated
     */
    int insertSelective(ManageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_log
     *
     * @mbggenerated
     */
    ManageLog selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageLog record);
}