package com.hurricane.coupon.dao;

import com.hurricane.coupon.entity.SellerTypeDict;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface SellerTypeDictMapper {

    List<Map<String, Object>> getSellerTypeList(HashMap<String, Object> map);

    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_type_dict
     *
     * @mbggenerated
     */
    int insert(SellerTypeDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_type_dict
     *
     * @mbggenerated
     */
    int insertSelective(SellerTypeDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_type_dict
     *
     * @mbggenerated
     */
    SellerTypeDict selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_type_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SellerTypeDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_type_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SellerTypeDict record);
}