package com.hurricane.coupon.entity;

import java.io.Serializable;
import java.util.Date;

public class Coupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.derate_amount
     *
     * @mbggenerated
     */
    private String derateAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.end_time
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.use_explain
     *
     * @mbggenerated
     */
    private String useExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.activity_link_url
     *
     * @mbggenerated
     */
    private String activityLinkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.is_overdue
     *
     * @mbggenerated
     */
    private String isOverdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.is_recom
     *
     * @mbggenerated
     */
    private String isRecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.receive_num
     *
     * @mbggenerated
     */
    private Integer receiveNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.unreceive_num
     *
     * @mbggenerated
     */
    private Integer unreceiveNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.total
     *
     * @mbggenerated
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.sort
     *
     * @mbggenerated
     */
    private String sort;

    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.seller_uuid
     *
     * @mbggenerated
     */
    private String sellerUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.uuid
     *
     * @return the value of coupon.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.uuid
     *
     * @param uuid the value for coupon.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.name
     *
     * @return the value of coupon.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.name
     *
     * @param name the value for coupon.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.derate_amount
     *
     * @return the value of coupon.derate_amount
     *
     * @mbggenerated
     */
    public String getDerateAmount() {
        return derateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.derate_amount
     *
     * @param derateAmount the value for coupon.derate_amount
     *
     * @mbggenerated
     */
    public void setDerateAmount(String derateAmount) {
        this.derateAmount = derateAmount == null ? null : derateAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.start_time
     *
     * @return the value of coupon.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.start_time
     *
     * @param startTime the value for coupon.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.end_time
     *
     * @return the value of coupon.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.end_time
     *
     * @param endTime the value for coupon.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.use_explain
     *
     * @return the value of coupon.use_explain
     *
     * @mbggenerated
     */
    public String getUseExplain() {
        return useExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.use_explain
     *
     * @param useExplain the value for coupon.use_explain
     *
     * @mbggenerated
     */
    public void setUseExplain(String useExplain) {
        this.useExplain = useExplain == null ? null : useExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.activity_link_url
     *
     * @return the value of coupon.activity_link_url
     *
     * @mbggenerated
     */
    public String getActivityLinkUrl() {
        return activityLinkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.activity_link_url
     *
     * @param activityLinkUrl the value for coupon.activity_link_url
     *
     * @mbggenerated
     */
    public void setActivityLinkUrl(String activityLinkUrl) {
        this.activityLinkUrl = activityLinkUrl == null ? null : activityLinkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.type
     *
     * @return the value of coupon.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.type
     *
     * @param type the value for coupon.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.is_overdue
     *
     * @return the value of coupon.is_overdue
     *
     * @mbggenerated
     */
    public String getIsOverdue() {
        return isOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.is_overdue
     *
     * @param isOverdue the value for coupon.is_overdue
     *
     * @mbggenerated
     */
    public void setIsOverdue(String isOverdue) {
        this.isOverdue = isOverdue == null ? null : isOverdue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.is_recom
     *
     * @return the value of coupon.is_recom
     *
     * @mbggenerated
     */
    public String getIsRecom() {
        return isRecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.is_recom
     *
     * @param isRecom the value for coupon.is_recom
     *
     * @mbggenerated
     */
    public void setIsRecom(String isRecom) {
        this.isRecom = isRecom == null ? null : isRecom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.receive_num
     *
     * @return the value of coupon.receive_num
     *
     * @mbggenerated
     */
    public Integer getReceiveNum() {
        return receiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.receive_num
     *
     * @param receiveNum the value for coupon.receive_num
     *
     * @mbggenerated
     */
    public void setReceiveNum(Integer receiveNum) {
        this.receiveNum = receiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.unreceive_num
     *
     * @return the value of coupon.unreceive_num
     *
     * @mbggenerated
     */
    public Integer getUnreceiveNum() {
        return unreceiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.unreceive_num
     *
     * @param unreceiveNum the value for coupon.unreceive_num
     *
     * @mbggenerated
     */
    public void setUnreceiveNum(Integer unreceiveNum) {
        this.unreceiveNum = unreceiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.total
     *
     * @return the value of coupon.total
     *
     * @mbggenerated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.total
     *
     * @param total the value for coupon.total
     *
     * @mbggenerated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.sort
     *
     * @return the value of coupon.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.sort
     *
     * @param sort the value for coupon.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getSellerUuid() {
        return sellerUuid;
    }

    public void setSellerUuid(String sellerUuid) {
        this.sellerUuid = sellerUuid == null ? null : sellerUuid.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null :status.trim();
    }
}