package com.hurricane.coupon.entity;

import java.io.Serializable;
import java.util.Date;

public class CouponLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_log.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_log.accept_time
     *
     * @mbggenerated
     */
    private Date acceptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_log.accepter_ip
     *
     * @mbggenerated
     */
    private String accepterIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_log.accepter_port
     *
     * @mbggenerated
     */
    private String accepterPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_log.coupon_info_uuid
     *
     * @mbggenerated
     */
    private String couponInfoUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_log.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_log.uuid
     *
     * @return the value of coupon_log.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_log.uuid
     *
     * @param uuid the value for coupon_log.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_log.accept_time
     *
     * @return the value of coupon_log.accept_time
     *
     * @mbggenerated
     */
    public Date getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_log.accept_time
     *
     * @param acceptTime the value for coupon_log.accept_time
     *
     * @mbggenerated
     */
    public void setAcceptTime(Date acceptTime) {
        this.acceptTime = acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_log.accepter_ip
     *
     * @return the value of coupon_log.accepter_ip
     *
     * @mbggenerated
     */
    public String getAccepterIp() {
        return accepterIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_log.accepter_ip
     *
     * @param accepterIp the value for coupon_log.accepter_ip
     *
     * @mbggenerated
     */
    public void setAccepterIp(String accepterIp) {
        this.accepterIp = accepterIp == null ? null : accepterIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_log.accepter_port
     *
     * @return the value of coupon_log.accepter_port
     *
     * @mbggenerated
     */
    public String getAccepterPort() {
        return accepterPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_log.accepter_port
     *
     * @param accepterPort the value for coupon_log.accepter_port
     *
     * @mbggenerated
     */
    public void setAccepterPort(String accepterPort) {
        this.accepterPort = accepterPort == null ? null : accepterPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_log.coupon_info_uuid
     *
     * @return the value of coupon_log.coupon_info_uuid
     *
     * @mbggenerated
     */
    public String getCouponInfoUuid() {
        return couponInfoUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_log.coupon_info_uuid
     *
     * @param couponInfoUuid the value for coupon_log.coupon_info_uuid
     *
     * @mbggenerated
     */
    public void setCouponInfoUuid(String couponInfoUuid) {
        this.couponInfoUuid = couponInfoUuid == null ? null : couponInfoUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_log.openid
     *
     * @return the value of coupon_log.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_log.openid
     *
     * @param openid the value for coupon_log.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}