package com.hurricane.coupon.entity;

import java.io.Serializable;
import java.util.Date;

public class Seller implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.logo_pic_url
     *
     * @mbggenerated
     */
    private String logoPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.site_url
     *
     * @mbggenerated
     */
    private String siteUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.short_url
     *
     * @mbggenerated
     */
    private String shortUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.long_url
     *
     * @mbggenerated
     */
    private String longUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.uuid
     *
     * @return the value of seller.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.uuid
     *
     * @param uuid the value for seller.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.name
     *
     * @return the value of seller.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.name
     *
     * @param name the value for seller.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.logo_pic_url
     *
     * @return the value of seller.logo_pic_url
     *
     * @mbggenerated
     */
    public String getLogoPicUrl() {
        return logoPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.logo_pic_url
     *
     * @param logoPicUrl the value for seller.logo_pic_url
     *
     * @mbggenerated
     */
    public void setLogoPicUrl(String logoPicUrl) {
        this.logoPicUrl = logoPicUrl == null ? null : logoPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.site_url
     *
     * @return the value of seller.site_url
     *
     * @mbggenerated
     */
    public String getSiteUrl() {
        return siteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.site_url
     *
     * @param siteUrl the value for seller.site_url
     *
     * @mbggenerated
     */
    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl == null ? null : siteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.source
     *
     * @return the value of seller.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.source
     *
     * @param source the value for seller.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.status
     *
     * @return the value of seller.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.status
     *
     * @param status the value for seller.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.short_url
     *
     * @return the value of seller.short_url
     *
     * @mbggenerated
     */
    public String getShortUrl() {
        return shortUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.short_url
     *
     * @param shortUrl the value for seller.short_url
     *
     * @mbggenerated
     */
    public void setShortUrl(String shortUrl) {
        this.shortUrl = shortUrl == null ? null : shortUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.long_url
     *
     * @return the value of seller.long_url
     *
     * @mbggenerated
     */
    public String getLongUrl() {
        return longUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.long_url
     *
     * @param longUrl the value for seller.long_url
     *
     * @mbggenerated
     */
    public void setLongUrl(String longUrl) {
        this.longUrl = longUrl == null ? null : longUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.create_time
     *
     * @return the value of seller.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.create_time
     *
     * @param createTime the value for seller.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.sort
     *
     * @return the value of seller.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.sort
     *
     * @param sort the value for seller.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.remark
     *
     * @return the value of seller.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.remark
     *
     * @param remark the value for seller.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}