package com.hurricane.coupon.entity;

import java.io.Serializable;

public class UserLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.login_time
     *
     * @mbggenerated
     */
    private String loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.login_Ip
     *
     * @mbggenerated
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.login_port
     *
     * @mbggenerated
     */
    private String loginPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.uuid
     *
     * @return the value of user_log.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.uuid
     *
     * @param uuid the value for user_log.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.login_time
     *
     * @return the value of user_log.login_time
     *
     * @mbggenerated
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.login_time
     *
     * @param loginTime the value for user_log.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime == null ? null : loginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.login_Ip
     *
     * @return the value of user_log.login_Ip
     *
     * @mbggenerated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.login_Ip
     *
     * @param loginIp the value for user_log.login_Ip
     *
     * @mbggenerated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.login_port
     *
     * @return the value of user_log.login_port
     *
     * @mbggenerated
     */
    public String getLoginPort() {
        return loginPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.login_port
     *
     * @param loginPort the value for user_log.login_port
     *
     * @mbggenerated
     */
    public void setLoginPort(String loginPort) {
        this.loginPort = loginPort == null ? null : loginPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.open_id
     *
     * @return the value of user_log.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.open_id
     *
     * @param openId the value for user_log.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }
}