package com.hurricane.coupon.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.figureurl
     *
     * @mbggenerated
     */
    private String figureurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.figureurl_1
     *
     * @mbggenerated
     */
    private String figureurl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.figureurl_2
     *
     * @mbggenerated
     */
    private String figureurl2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.figureurl_qq_1
     *
     * @mbggenerated
     */
    private String figureurlQq1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.figureurl_qq_2
     *
     * @mbggenerated
     */
    private String figureurlQq2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_lost
     *
     * @mbggenerated
     */
    private String isLost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_yellow_vip
     *
     * @mbggenerated
     */
    private String isYellowVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_yellow_year_vip
     *
     * @mbggenerated
     */
    private String isYellowYearVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ret
     *
     * @mbggenerated
     */
    private String ret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.vip
     *
     * @mbggenerated
     */
    private String vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.yellow_vip_level
     *
     * @mbggenerated
     */
    private String yellowVipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uuid
     *
     * @return the value of user.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uuid
     *
     * @param uuid the value for user.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.figureurl
     *
     * @return the value of user.figureurl
     *
     * @mbggenerated
     */
    public String getFigureurl() {
        return figureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.figureurl
     *
     * @param figureurl the value for user.figureurl
     *
     * @mbggenerated
     */
    public void setFigureurl(String figureurl) {
        this.figureurl = figureurl == null ? null : figureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.figureurl_1
     *
     * @return the value of user.figureurl_1
     *
     * @mbggenerated
     */
    public String getFigureurl1() {
        return figureurl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.figureurl_1
     *
     * @param figureurl1 the value for user.figureurl_1
     *
     * @mbggenerated
     */
    public void setFigureurl1(String figureurl1) {
        this.figureurl1 = figureurl1 == null ? null : figureurl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.figureurl_2
     *
     * @return the value of user.figureurl_2
     *
     * @mbggenerated
     */
    public String getFigureurl2() {
        return figureurl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.figureurl_2
     *
     * @param figureurl2 the value for user.figureurl_2
     *
     * @mbggenerated
     */
    public void setFigureurl2(String figureurl2) {
        this.figureurl2 = figureurl2 == null ? null : figureurl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.figureurl_qq_1
     *
     * @return the value of user.figureurl_qq_1
     *
     * @mbggenerated
     */
    public String getFigureurlQq1() {
        return figureurlQq1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.figureurl_qq_1
     *
     * @param figureurlQq1 the value for user.figureurl_qq_1
     *
     * @mbggenerated
     */
    public void setFigureurlQq1(String figureurlQq1) {
        this.figureurlQq1 = figureurlQq1 == null ? null : figureurlQq1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.figureurl_qq_2
     *
     * @return the value of user.figureurl_qq_2
     *
     * @mbggenerated
     */
    public String getFigureurlQq2() {
        return figureurlQq2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.figureurl_qq_2
     *
     * @param figureurlQq2 the value for user.figureurl_qq_2
     *
     * @mbggenerated
     */
    public void setFigureurlQq2(String figureurlQq2) {
        this.figureurlQq2 = figureurlQq2 == null ? null : figureurlQq2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_lost
     *
     * @return the value of user.is_lost
     *
     * @mbggenerated
     */
    public String getIsLost() {
        return isLost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_lost
     *
     * @param isLost the value for user.is_lost
     *
     * @mbggenerated
     */
    public void setIsLost(String isLost) {
        this.isLost = isLost == null ? null : isLost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_yellow_vip
     *
     * @return the value of user.is_yellow_vip
     *
     * @mbggenerated
     */
    public String getIsYellowVip() {
        return isYellowVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_yellow_vip
     *
     * @param isYellowVip the value for user.is_yellow_vip
     *
     * @mbggenerated
     */
    public void setIsYellowVip(String isYellowVip) {
        this.isYellowVip = isYellowVip == null ? null : isYellowVip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_yellow_year_vip
     *
     * @return the value of user.is_yellow_year_vip
     *
     * @mbggenerated
     */
    public String getIsYellowYearVip() {
        return isYellowYearVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_yellow_year_vip
     *
     * @param isYellowYearVip the value for user.is_yellow_year_vip
     *
     * @mbggenerated
     */
    public void setIsYellowYearVip(String isYellowYearVip) {
        this.isYellowYearVip = isYellowYearVip == null ? null : isYellowYearVip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.level
     *
     * @return the value of user.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.level
     *
     * @param level the value for user.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.msg
     *
     * @return the value of user.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.msg
     *
     * @param msg the value for user.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province
     *
     * @return the value of user.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province
     *
     * @param province the value for user.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ret
     *
     * @return the value of user.ret
     *
     * @mbggenerated
     */
    public String getRet() {
        return ret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ret
     *
     * @param ret the value for user.ret
     *
     * @mbggenerated
     */
    public void setRet(String ret) {
        this.ret = ret == null ? null : ret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.source
     *
     * @return the value of user.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.source
     *
     * @param source the value for user.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.vip
     *
     * @return the value of user.vip
     *
     * @mbggenerated
     */
    public String getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.vip
     *
     * @param vip the value for user.vip
     *
     * @mbggenerated
     */
    public void setVip(String vip) {
        this.vip = vip == null ? null : vip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.year
     *
     * @return the value of user.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.year
     *
     * @param year the value for user.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.yellow_vip_level
     *
     * @return the value of user.yellow_vip_level
     *
     * @mbggenerated
     */
    public String getYellowVipLevel() {
        return yellowVipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.yellow_vip_level
     *
     * @param yellowVipLevel the value for user.yellow_vip_level
     *
     * @mbggenerated
     */
    public void setYellowVipLevel(String yellowVipLevel) {
        this.yellowVipLevel = yellowVipLevel == null ? null : yellowVipLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.openid
     *
     * @return the value of user.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.openid
     *
     * @param openid the value for user.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}